version: '3.9'
services:
  web:
    container_name: my-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      volumes:
        - /app/node_modules
        - .:/app
      command: ["npm", "run", "test"]