name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: frontend
        file: frontend/Dockerfile.dev
        tags: tomersf/docker-react:latest
        outputs: type=docker,dest=/tmp/myimage.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: myimage
        path: /tmp/myimage.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: myimage
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/myimage.tar
          docker image ls -a

      - name: Run tests
        run: docker run tomersf/docker-react npm run test -- --run

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate frontend deployment package
        run: zip -r deploy.zip frontend -x 'frontend/.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          version_label: 12345
          region: eu-central-1
          deployment_package: deploy.zip

