name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t tomersf/docker-react -f Dockerfile.dev ./frontend
      
    - name: Run tests
      run: docker run tomersf/docker-react npm run test -- --run
